/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2024 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_KMPPPFXERR_H
# define HEADER_KMPPPFXERR_H

# define KMPPPFXerr(f, r) ERR_KMPPPFX_error((f), (r), __FILE__, __LINE__)


# ifdef  __cplusplus
extern "C" {
# endif
int ERR_load_KMPPPFX_strings(void);
void ERR_unload_KMPPPFX_strings(void);
void ERR_KMPPPFX_error(int function, int reason, char *file, int line);
# ifdef  __cplusplus
}
# endif

/*
 * KMPPPFX function codes.
 */
# define KMPPPFX_F_CTRL                                   100
# define KMPPPFX_F_CTX_NEW                                101
# define KMPPPFX_F_EC_KEY_SIGN                            108
# define KMPPPFX_F_EC_KEY_SIGN_SETUP                      109
# define KMPPPFX_F_EC_KEY_SIGN_SIG                        110
# define KMPPPFX_F_GET_PRIVATE_EC_KEY                     107
# define KMPPPFX_F_GET_PRIVATE_RSA                        106
# define KMPPPFX_F_INIT                                   102
# define KMPPPFX_F_INIT_SYMMETRIC                         115
# define KMPPPFX_F_INIT_SYMMETRIC_KEY                     116
# define KMPPPFX_F_LOAD                                   103
# define KMPPPFX_F_PKEY_METHS_INIT                        114
# define KMPPPFX_F_PKEY_RSA_SIGN                          113
# define KMPPPFX_F_RSA_PRIV_DEC                           104
# define KMPPPFX_F_RSA_PRIV_ENC                           105
# define KMPPPFX_F_RSA_SIGN                               112
# define KMPPPFX_F_SYMMETRIC_CIPHER                       117
# define KMPPPFX_F_SYMMETRIC_CTRL                         118
# define KMPPPFX_F_VTRACE                                 111

/*
 * KMPPPFX reason codes.
 */
# define KMPPPFX_R_ALLOC_FAILURE                          100
# define KMPPPFX_R_BIND_FAILURE                           121
# define KMPPPFX_R_CANT_FIND_KMPPPFX_CONTEXT              101
# define KMPPPFX_R_CANT_GET_KEY                           106
# define KMPPPFX_R_CANT_GET_METHOD                        107
# define KMPPPFX_R_CANT_GET_PADDING                       114
# define KMPPPFX_R_CANT_GET_RSA_MGF_MD                    118
# define KMPPPFX_R_CANT_GET_SALT_LENGTH                   115
# define KMPPPFX_R_CANT_GET_SIGNATURE_MD                  116
# define KMPPPFX_R_CIPHERS_INIT_STATIC_FAILED             127
# define KMPPPFX_R_CTX_NULL                               122
# define KMPPPFX_R_DATA_TOO_LARGE                         123
# define KMPPPFX_R_ENCRYPT_DECRYPT_FAILED                 124
# define KMPPPFX_R_ENGINE_NOT_INITIALIZED                 108
# define KMPPPFX_R_ENGINE_SET_CIPHERS_FAILED              126
# define KMPPPFX_R_FILE_OPEN_ERROR                        109
# define KMPPPFX_R_INVALID_EC_KEY                         111
# define KMPPPFX_R_INVALID_RSA                            110
# define KMPPPFX_R_INVALID_SIGNATURE_LENGTH               119
# define KMPPPFX_R_LOAD_PFX_PUBKEY_ERROR                  103
# define KMPPPFX_R_OPENSSL_INIT_CRYPTO_FAILED             125
# define KMPPPFX_R_PADDING_NOT_SUPPORTED                  117
# define KMPPPFX_R_PARSE_PFX_KEY_ID_ERROR                 102
# define KMPPPFX_R_PFX_OPEN_ERROR                         104
# define KMPPPFX_R_UNKNOWN_COMMAND                        113
# define KMPPPFX_R_UNSUPPORTED_KEY_ALGORITHM              112
# define KMPPPFX_R_UNSUPPORTED_KINV_R_PARAMS              120
# define KMPPPFX_R_UNSUPPORTED_SSL_CLIENT_CERT            105
#define  KMPPPFX_R_ENGINE_OPEN_INCOMPATIBLE_KEY           128

#endif
