/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2024 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <openssl/err.h>
#include "e_keyisopfx_err.h"

#ifndef OPENSSL_NO_ERR

static ERR_STRING_DATA KMPPPFX_str_functs[] = {
    {ERR_PACK(0, KMPPPFX_F_CTRL, 0), "kmpppfx_ctrl"},
    {ERR_PACK(0, KMPPPFX_F_CTX_NEW, 0), "kmpppfx_ctx_new"},
    {ERR_PACK(0, KMPPPFX_F_EC_KEY_SIGN, 0), "kmpppfx_ec_key_sign"},
    {ERR_PACK(0, KMPPPFX_F_EC_KEY_SIGN_SETUP, 0), "kmpppfx_ec_key_sign_setup"},
    {ERR_PACK(0, KMPPPFX_F_EC_KEY_SIGN_SIG, 0), "kmpppfx_ev_key_sign_sig"},
    {ERR_PACK(0, KMPPPFX_F_GET_PRIVATE_EC_KEY, 0),
     "kmpppfx_get_private_ec_key"},
    {ERR_PACK(0, KMPPPFX_F_GET_PRIVATE_RSA, 0), "kmpppfx_get_private_rsa"},
    {ERR_PACK(0, KMPPPFX_F_INIT, 0), "kmpppfx_init"},
    {ERR_PACK(0, KMPPPFX_F_INIT_SYMMETRIC, 0), "kmpppfx_init_symmetric"},
    {ERR_PACK(0, KMPPPFX_F_INIT_SYMMETRIC_KEY, 0),
     "kmpppfx_init_symmetric_key"},
    {ERR_PACK(0, KMPPPFX_F_LOAD, 0), "kmpppfx_load"},
    {ERR_PACK(0, KMPPPFX_F_PKEY_METHS_INIT, 0), "kmpppfx_pkey_meths_init"},
    {ERR_PACK(0, KMPPPFX_F_PKEY_RSA_SIGN, 0), "kmpppfx_pkey_rsa_sign"},
    {ERR_PACK(0, KMPPPFX_F_RSA_PRIV_DEC, 0), "kmpppfx_rsa_priv_dec"},
    {ERR_PACK(0, KMPPPFX_F_RSA_PRIV_ENC, 0), "kmpppfx_rsa_priv_enc"},
    {ERR_PACK(0, KMPPPFX_F_RSA_SIGN, 0), "kmpppfx_rsa_sign"},
    {ERR_PACK(0, KMPPPFX_F_SYMMETRIC_CIPHER, 0), "kmpppfx_symmetric_cipher"},
    {ERR_PACK(0, KMPPPFX_F_SYMMETRIC_CTRL, 0), "kmpppfx_symmetric_ctrl"},
    {ERR_PACK(0, KMPPPFX_F_VTRACE, 0), "kmpppfx_vtrace"},
    {0, NULL}
};

static ERR_STRING_DATA KMPPPFX_str_reasons[] = {
    {ERR_PACK(0, 0, KMPPPFX_R_ALLOC_FAILURE), "allocation failure"},
    {ERR_PACK(0, 0, KMPPPFX_R_BIND_FAILURE), "bind failure"},
    {ERR_PACK(0, 0, KMPPPFX_R_CANT_FIND_KMPPPFX_CONTEXT),
    "cant find kmpppfx context"},
    {ERR_PACK(0, 0, KMPPPFX_R_CANT_GET_KEY), "cant get key"},
    {ERR_PACK(0, 0, KMPPPFX_R_CANT_GET_METHOD), "cant get method"},
    {ERR_PACK(0, 0, KMPPPFX_R_CANT_GET_PADDING), "cant get padding"},
    {ERR_PACK(0, 0, KMPPPFX_R_CANT_GET_RSA_MGF_MD), "cant get RSA mgf md"},
    {ERR_PACK(0, 0, KMPPPFX_R_CANT_GET_SALT_LENGTH), "cant get salt length"},
    {ERR_PACK(0, 0, KMPPPFX_R_CANT_GET_SIGNATURE_MD), "cant get signature md"},
    {ERR_PACK(0, 0, KMPPPFX_R_CIPHERS_INIT_STATIC_FAILED),
    "ciphers init static failed"},
    {ERR_PACK(0, 0, KMPPPFX_R_CTX_NULL), "ctx null"},
    {ERR_PACK(0, 0, KMPPPFX_R_DATA_TOO_LARGE), "data too large"},
    {ERR_PACK(0, 0, KMPPPFX_R_ENCRYPT_DECRYPT_FAILED),
    "encrypt decrypt failed"},
    {ERR_PACK(0, 0, KMPPPFX_R_ENGINE_NOT_INITIALIZED),
    "engine not initialized"},
    {ERR_PACK(0, 0, KMPPPFX_R_ENGINE_SET_CIPHERS_FAILED),
    "engine set ciphers failed"},
    {ERR_PACK(0, 0, KMPPPFX_R_FILE_OPEN_ERROR), "file open error"},
    {ERR_PACK(0, 0, KMPPPFX_R_INVALID_EC_KEY), "invalid EC_KEY"},
    {ERR_PACK(0, 0, KMPPPFX_R_INVALID_RSA), "invalid RSA"},
    {ERR_PACK(0, 0, KMPPPFX_R_INVALID_SIGNATURE_LENGTH),
    "invalid signature length"},
    {ERR_PACK(0, 0, KMPPPFX_R_LOAD_PFX_PUBKEY_ERROR),
    "load pfx public key error"},
    {ERR_PACK(0, 0, KMPPPFX_R_OPENSSL_INIT_CRYPTO_FAILED),
    "openssl init crypto failed"},
    {ERR_PACK(0, 0, KMPPPFX_R_PADDING_NOT_SUPPORTED), "padding not supported"},
    {ERR_PACK(0, 0, KMPPPFX_R_PARSE_PFX_KEY_ID_ERROR), "parse keyId error"},
    {ERR_PACK(0, 0, KMPPPFX_R_PFX_OPEN_ERROR), "pfx open error"},
    {ERR_PACK(0, 0, KMPPPFX_R_UNKNOWN_COMMAND), "unknown command"},
    {ERR_PACK(0, 0, KMPPPFX_R_UNSUPPORTED_KEY_ALGORITHM),
    "unsupported key algorithm"},
    {ERR_PACK(0, 0, KMPPPFX_R_UNSUPPORTED_KINV_R_PARAMS),
    "unsupported kinv r params"},
    {ERR_PACK(0, 0, KMPPPFX_R_UNSUPPORTED_SSL_CLIENT_CERT),
    "unsupported ssl client cert"},
    {0, NULL}
};

#endif

static int lib_code = 0;
static int error_loaded = 0;

int ERR_load_KMPPPFX_strings(void)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();

    if (!error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_load_strings(lib_code, KMPPPFX_str_functs);
        ERR_load_strings(lib_code, KMPPPFX_str_reasons);
#endif
        error_loaded = 1;
    }
    return 1;
}

void ERR_unload_KMPPPFX_strings(void)
{
    if (error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_unload_strings(lib_code, KMPPPFX_str_functs);
        ERR_unload_strings(lib_code, KMPPPFX_str_reasons);
#endif
        error_loaded = 0;
    }
}

void ERR_KMPPPFX_error(int function, int reason, char *file, int line)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();
    ERR_PUT_error(lib_code, function, reason, file, line);
}
