name: Build and Test All Flags - UBUNTU 22.04

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config cmake libcurl4-openssl-dev libglib2.0-dev libgtest-dev libdbus-1-dev uuid-dev libssl-dev build-essential googletest libtss2-dev libjansson4 
        curl -sSL -O https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb 
        sudo rm packages-microsoft-prod.deb 
        sudo apt-get update 
        echo "deb https://packages.microsoft.com/ubuntu/20.04/prod testing main" | sudo tee /etc/apt/sources.list.d/microsoft-test.list 
        sudo apt-get update 
        sudo apt install -y symcrypt 

    # Loop through all flags
    - name: Test KMPP_DEBUG
      run: |
        ./scripts/create_certs.sh
        cmake -S . -B build -DKMPP_DEBUG=ON
        cmake --build build
        chmod +x scripts/postinst scripts/preinst
        sh scripts/preinst
        sudo make install -C build
        sudo sh scripts/postinst
        rm -rf certs
        ./example/generate_pfx.sh
        ./build/bin/kmppexample

    - name: Test KMPP_OPENSSL_SUPPORT
      run: |
        ./scripts/create_certs.sh
        rm -rf build  # Clean the build directory
        cmake -S . -B build -DKMPP_OPENSSL_SUPPORT=OFF
        cmake --build build
        chmod +x scripts/postinst scripts/preinst
        sh scripts/preinst
        sudo make install -C build
        sudo sh scripts/postinst
        rm -rf certs
        ./example/generate_pfx.sh
        ./build/bin/kmppexample

    - name: Test KMPP_SYMMETRIC_KEY_SUPPORT
      run: |
        ./scripts/create_certs.sh
        rm -rf build  # Clean the build directory      
        cmake -S . -B build -DKMPP_SYMMETRIC_KEY_SUPPORT=OFF
        cmake --build build
        chmod +x scripts/postinst scripts/preinst
        sh scripts/preinst
        sudo make install -C build
        sudo sh scripts/postinst
        rm -rf certs
        ./example/generate_pfx.sh
        ./build/bin/kmppexample

    - name: Test KMPP_INSTALL_SERVICE
      run: |
        ./scripts/create_certs.sh
        rm -rf build  # Clean the build directory
        cmake -S . -B build -DKMPP_INSTALL_SERVICE=OFF
        cmake --build build
        chmod +x scripts/postinst scripts/preinst
        sh scripts/preinst
        sudo make install -C build
        sudo sh scripts/postinst
        rm -rf certs
        ./example/generate_pfx.sh
        ./build/bin/kmppexample
